# Generated by Django 5.0.4 on 2024-05-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
    ]
