# Generated by Django 5.0.4 on 2024-05-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
